### ISSUE TITLE
Exception thrown when opening an XBee device configured in API 2

### ISSUE THREAD

**Issue by tatianaleon** [digidotcom/XBeeJavaLibrary#27]
When a module is configured to use API 2 (API Mode with Escapes), that is `AP = 2`, an exception is thrown when opening the device and reading the device information.

Using the **SendDataSample** example of the **XBee Java Library v1.0.1**, this is what is printed out:

```
 +--------------------------------------+
 |  XBee Java Library Send Data Sample  |
 +--------------------------------------+

WARNING:  RXTX Version mismatch
	Jar version = RXTX-2.2pre1
	native lib Version = RXTX-2.2pre2
Error
com.digi.xbee.api.exceptions.TimeoutException: There was a timeout while executing the requested operation.
	at com.digi.xbee.api.AbstractXBeeDevice.sendXBeePacket(AbstractXBeeDevice.java:989)
	at com.digi.xbee.api.AbstractXBeeDevice.sendATCommand(AbstractXBeeDevice.java:806)
	at com.digi.xbee.api.AbstractXBeeDevice.sendParameter(AbstractXBeeDevice.java:1983)
	at com.digi.xbee.api.AbstractXBeeDevice.getParameter(AbstractXBeeDevice.java:1925)
	at com.digi.xbee.api.AbstractXBeeDevice.readDeviceInfo(AbstractXBeeDevice.java:365)
	at com.digi.xbee.api.XBeeDevice.open(XBeeDevice.java:219)
	at com.digi.xbee.api.senddata.MainApp.main(MainApp.java:55)
```

**Comment by tatianaleon** [comment]
Fixed in master.

See commit: https://github.com/digidotcom/XBeeJavaLibrary/commit/0aee43fc52c7b23d1c75f70dd6aa7a22c9bf66f8
